// <auto-generated />
using AutopartsRepository.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutopartsRepository.Migrations
{
    [DbContext(typeof(AutopartsDbContext))]
    [Migration("20231113153855_TestWarranty")]
    partial class TestWarranty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutopartsEntity.Catalog.Entities.Warranty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreateDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdateDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Warranties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = "13.11.2023",
                            IsActive = true,
                            Title = "6 měsíců"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = "13.11.2023",
                            IsActive = true,
                            Title = "12 měsíců"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = "13.11.2023",
                            IsActive = true,
                            Title = "24 měsíců"
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = "13.11.2023",
                            IsActive = true,
                            Title = "36 měsíců"
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = "13.11.2023",
                            IsActive = true,
                            Title = "48 měsíců"
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = "13.11.2023",
                            IsActive = true,
                            Title = "60 měsíců"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
